### ISSUE TITLE
Incorrect version of the application shown in files sometimes

### ISSUE THREAD

**Issue by piiskop** [ONLYOFFICE/DocumentServer#1036]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
Incorrect application versions are shown in some files.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a file in an old version of ONLYOFFICE, upgrade ONLYOFFICE, check the version of the application _Home_ -> _Document Info..._, see that the version is old! If you do it after the upgrade and create a new file then it shows something with _EXCEL_ or _WORD_, not _ONLYOFFICE_. Let some time pass and it shows _ONLYOFFICE_!
**What is the expected behavior?**
I expect the version to be shown correctly each time.
**Did this work in previous versions of DocumentServer?**
No.
**DocumentServer version:**
6
**Operating System:**
_Ubuntu_
**Browser version:**
86.0.4240.75 (Official Build) (64-bit)
**Additional information**
This issue is a follow-up of the issue on [_SUMIFS_](https://github.com/ONLYOFFICE/DocumentServer/issues/1032#issuecomment-712672201). There's also another problem: _SUMIFS_ was corrected but that change isn't listed in the change log.

**Comment by ShockwaveNN** [comment]
ONLYOFFICE DocumentServer is not creating empty new document, it's just use default empty file, which is stored in integration (for example Nextcloud or OwnCloud), so I think this new empty file was created in MS Excel

But if you save this file - in next open it should show ONLYOFFICE

**Comment by piiskop** [comment]
Then the reason with the delay is _Nextcloud_ as it servers my _ONLYOFFICE_. This however doesn't explain why files created by old version of _ONLYOFFICE_ show the old application version in new _ONLYOFFICE_. Is the reason for that also that _Nextcloud_ manages the version info?

**Comment by ShockwaveNN** [comment]
Could you just create a new file. do not open it in ONLYOFFICE, only create it. Download it and attach to this issue. I can take a look at this file to be sure, which Editor info is stored in file itself

**Comment by piiskop** [comment]
I did what you asked: created a new file, did not open it in _ONLYOFFICE_, downloaded it but I see no option here to attach it. However, you can do your own [download](https://nextcloud.tennis24.ee/index.php/s/WfC2bmBSj944aYg) directly from _Nextcloud_.

**Comment by ShockwaveNN** [comment]
Ok got this file (you can zip this file and this allow to attach any file to github)

If you extract this file as zip file you can open `docProps/app.xml` file and see this info:

![image](https://user-images.githubusercontent.com/668524/96592467-17c2e900-12f1-11eb-8e35-b2c651183009.png)

This is same version we show in ONLYOFFICE DocumentServer
![image](https://user-images.githubusercontent.com/668524/96592590-3b862f00-12f1-11eb-9f49-6c907a9766b9.png)

But if you edit this file, close it, wait for around minute and open it again - we override this info with our own

![image](https://user-images.githubusercontent.com/668524/96592721-5f497500-12f1-11eb-9509-bd3f87db5f58.png)

**Comment by piiskop** [comment]
I couldn't find a way to attach something in GitHub. It's made unintuitive here - no clearly discoverable button. However, now I see that below the post, there's a text that I can attach by dragging & dropping, selecting or pasting them - so this is a button but I expect such a button to appear on the formatting bar or being similar to the two buttons below the post. It just looks like an information bar.

Finding the information as XML works. Waiting for a while for the correct version to appear works. What doesn't work is that for files created in an old version, the application version info remains old - wait however you like!

**Comment by ShockwaveNN** [comment]
> What doesn't work is that for files created in an old version, the application version info remains old - wait however you like!

Just checked DocumentServer 5.6.5.3 and it's show Excel for new file and ONLYOFFICE/5.6.5.3 for edited file

If you got some version older - old behaviour may be a bug and we fixed it and in current version v6.0.0 behavior is correct

**Comment by piiskop** [comment]
I have _6_ and it still shows _5.6_ for old edited files. Even if I edit the files in _6_ it still shows _5.6_.

**Comment by ShockwaveNN** [comment]
Could you upload some of those files to take a look?

**Comment by piiskop** [comment]
Have a look in the file [õpetajate-päev](https://nextcloud.tennis24.ee/index.php/s/NiccpZtW2n3aRwZ)!

**Comment by ShockwaveNN** [comment]
I've just checked this file using DocumentServer test example and DocumentServer v6.0.0 and everything seems fine for me:

![video](https://user-images.githubusercontent.com/668524/96610251-151dbf00-1304-11eb-9068-faa7efcb6744.gif)

**Comment by piiskop** [comment]
I see that it works in your environment. I did the same in my environment: writing "test" in a cell, waited until the disk icon greyed out, did a reload, "test" was there, application version was still _5.6_. Is it because _Nextcloud_ doesn't allow the version info change or is it _ONLYOFFICE_ internal?

**Comment by ShockwaveNN** [comment]
To be sure could you record a video of same process?

And add a screen of your nextcloud onlyoffice extension settings

**Comment by piiskop** [comment]
I was about to make the video requested by you as I discovered that I had the same file open in another computer as well. So I closed the file in both computers, reopened the file and the version info is correct. It's just confusing that the version info doesn't appear in real time but with a delay.
