### ISSUE TITLE
German date format

### ISSUE THREAD

**Issue by kleener** [ONLYOFFICE/DocumentServer#1073]
Hello,
Since version 6.0 you can add dates in the Document Editor in the text files.
In Germany, the date is usually given as DD.MM:YYYY.
In version 6.0.2 you can only add the date as MM.DD.YYYY.
It would be nice if that changed.

Maybe the link will help:
https://www.germanpod101.com/blog/2019/12/20/dates-in-german/

**Comment by Rita-Bubnova** [comment]
Hello, @kleener.
I can confirm - this is bug, issue 46301 in our private issue tracker.

**Comment by MatzeDE** [comment]
Just installed ONLYOFFICE Desktop Editors Version 6.3.1.56 and oh wonder: This bug was **not** fixed. Sigh! :-(
PLEASE, fix it as soon as possible. I can not understand why the date function works properly in the spreadsheet editor for all the locales, but not in the document editor!

Today is July 17, 2021. I just insert three different formats all with Language German. And this is the result:

Juli 17, 2021  --> FAIL. It should be: **17. Juli 2021**
7/17/21         --> FAIL. It should be: **17/7/21**
7.17.2021      --> FAIL. It should be: **17.7.2021**

It would be nice to have an additional format with leading zeros like this: 17.**0**7.2021 or this 17/**0**7/2021 or this 17.**0**7.21 a.s.o.

Again, PLEASE fix it. BTW I think this problem still exists for other languages too.

Regards from Berlin / Germany / Europe / Earth.

**Comment by ShockwaveNN** [comment]
@MatzeDE Sorry to hear this, but not this issue still not fixed, I'll try to get our developers attention on this
Seems fix for issue is rather complicated, so it's still actual

**Comment by MatzeDE** [comment]
**PROBLEM SOLVED!**

Just installed ONLYOFFICE Desktop Editors Version 7.0.0: No problems with German dates in the document editor anymore. Thanks to all of you. :-)

Regards from Berlin / Germany

**Comment by ShockwaveNN** [comment]
I'll leave this issue open because seems some cases for some languages will be resolved only in v7.1.0

**Comment by shu0406** [comment]
Also a bug regarding german date: 
If you insert german dates it looks fine in OO (image1) however in WORD 2016 it either breaks the date or completly disappears (image2). The only writing that works fine is the first writing while the option to autoupdate ist not active:
ONLYOFFICE
![grafik](https://user-images.githubusercontent.com/76654412/159473926-02cf0222-c8dc-46bc-9acc-0cadcceb24bc.png)
WORD
![grafik](https://user-images.githubusercontent.com/76654412/159474062-d1bb7b99-4b5b-4987-942e-b590025c9fc9.png)

**Comment by ShockwaveNN** [comment]
@shu0406 Could you create a new issue, I think most of user cases of original issue for German should be resolved, so it may be something new

**Comment by shu0406** [comment]
Hi, 
unfortunately the date is still wrong in presentation mode in v7.1.0. In textdocuments it is correct!
Textdocument:
![grafik](https://user-images.githubusercontent.com/76654412/168593384-88b77fe5-8891-4cf9-8a3a-0a0a7224b4fe.png)
Presentation:
![grafik](https://user-images.githubusercontent.com/76654412/168593461-60366437-d09a-4d24-b778-427e2f553d86.png)

**Comment by ShockwaveNN** [comment]
@shu0406 Thanks for feedback, I can confirm that issue is not fully resolved

**Comment by shu0406** [comment]
Unfortunatly it is still wrong in presentation mode in Desktop Editor v.7.3.0

**Comment by skranz1982** [comment]
I can confirm this still happens in spreadsheets in v9.0.4.50 running on Bazzite 42. I used an export from my banking account via .csv and saved it as an .ods-file.

Screenshot with examples and explanations are as follows:

<img width="227" height="581" alt="Image" src="https://github.com/user-attachments/assets/7e9dbaa0-82f4-4de8-a861-ac18e528fad7" />

Most of those dates are correct, but some are wrongly interpreted/translated from German format. For example:

- "02.05.2025" looks like the 2nd of May, 2025, but actually IS the 5th of February, 2025.
- The same happened with "03.05.2025" which looks like the 3rd of May, 2025, but IS the 5th of March, 2025.
- "06.10.2025" looks like the 6th of October 2025 but IS 10th of June 2025 (today's 16.09.25 or 09/16/25).

This also happens in LibreOffice, btw, so I double checked my Bazzite settings but those look fine to me:

<img width="1226" height="699" alt="Image" src="https://github.com/user-attachments/assets/470c511a-f78a-40cf-8733-db9c51775caa" />

Best regards,
-seb

**Comment by VladimirProkofiev52** [comment]
Hello! @skranz1982 
I can confirm - this is a bug 77811.
We are aware of this issue, and our specialists are already working on fixing it.
In the future, please create separate issues for each problem so we can respond to them more quickly.
Thank you for your report.

**Comment by VladimirProkofiev52** [comment]
Hello! @shu0406 The current editor version is 9.1, and I wasn't able to reproduce your issue.
Please let me know if it’s still relevant.

**Comment by shu0406** [comment]
@VladimirProkofiev52 my issues are solved. Haven't tested @skranz1982 issues.
