### ISSUE TITLE
Incorrect table placement in this .docx file

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#1171]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
**What is the current behavior?**
The attached .docx file displays badly in OnlyOffice.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Open the attached .docx file in Word (2016)
* Open the same file in OO 6.1.0
* Compare

**What is the expected behavior?**
The .docx file should look the same in Word and OO.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
6.1.0 on Debian 11 Bullseye.
[bug-table.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/6063812/bug-table.docx)

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by parrenin** [comment]
The file displays better now.
The table inside the cells displays correctly, except that it is drawn using plain lines instead of dashed lines.

**Comment by ShockwaveNN** [comment]
@parrenin Yeah, it may be better, but issue 48943 still not fully resolved

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
We checked this bug in ONLYOFFICE Document Server version 8.0.

DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by parrenin** [comment]
Dear @Rita-Bubnova, the problem is not completely fixed.
Indeed, the table appears with plain lines in OO but with dashed lines in Word.
Should I open a new issue?

**Comment by Rita-Bubnova** [comment]
@parrenin, Yes, please create a new issue.
