### ISSUE TITLE
Copy/paste doesn't update reference cell when referencing another sheet.

### ISSUE THREAD

**Issue by Haplo064** [ONLYOFFICE/DocumentServer#122]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When you copy a cell with a formula referencing another sheet, and then paste that cell, the cell doesn't update the other sheet cell to the expected new value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Copy a cell with a formula referencing another sheets cell, and paste that cell somewhere else. The cell is identical to the first cell, instead of updating the cell.

**What is the expected behavior?**
Update the cell reference.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

All browsers. Current DocumentServer. Don't know if it worked previously.

In example, copying: CellB2 [=sheet1!A1] and pasting it to CellB3, should change the cell to [=sheet1!A2] but it leaves it as [=sheet1!A1]

**Comment by JohnPerkin** [comment]
Hello @Haplo064!
This is a bug which was already fixed in Document Server 4.3. We checked this scenario on 4.3.3 release and it worked as it is expected. Please check if your installation is up-to-date.

**Comment by Haplo064** [comment]
Thanks John, We will update the doc server and hopefully the issue will be cleared. I'll close this off now.

**Comment by Haplo064** [comment]
We finally had time to update the test environment, up to 4.3.5, and the issue is still withstanding.

Steps attempted:

On sheet1.
Fill Cell A1 with '1', Cell A2 with '2'.
Select cell C1, enter =A1
Cope Cell C1, paste into Cell C2.
Cell C2 has =A2, as expected.

Create a new sheet. (sheet2)

Select cell A1 on sheet2.
Enter =sheet1!A1
Cell shows '1'.
Copy cell A1 on sheet2, paste into cell A2.
Cell A2 shows '1', and has =sheet1!A1.

What is expected is that cell A2 on sheet2 should be sheet1!A2, and show '2' in this example.

**Comment by Haplo064** [comment]
Is there anyone who can look at this?

**Comment by ShockwaveNN** [comment]
Hi there. Seems that it is another bug. We try to fix it in next version.

**Comment by ShockwaveNN** [comment]
Issue fixed in 5.1.0 so closing it
