### ISSUE TITLE
Equation splitted on two lines

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2173]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.0

### Expected Behavior

OO should not split equations on two different lines.

### Actual Behavior

OO sometimes split equations on two different lines.

### Reproduction Steps

Steps to reproduce:
- open the attached .docx file in OO
- open it in Word
- Compare

[equation-on-2-lines.docx](https://github.com/ONLYOFFICE/DocumentServer/files/10993710/equation-on-2-lines.docx)

**Comment by TatianaKirillova** [comment]
Hello, @parrenin
Thanks for your request!
I can confirm that the problem exists. I created ticket 61653 in our private  tracker with your  issue.

**Comment by TatianaKirillova** [comment]
Hello, @parrenin 
I have good news!
The problem has been fixed by [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/4fc72505be578817c07c05225864f9ac2c5c3757
) and will be included in the next release.

**Comment by parrenin** [comment]
Sorry for the late answer, I had an issue with my github and was not receiving notifications...
I disagree, this issue is NOT fixed.
Please compare the display of the .docx file in the original report in Word and OO.
In one case, the minus sign is at the end of the line, and in the other it is at the beginning of the following line.

**Comment by TatianaKirillova** [comment]
@parrenin Indeed, the problem with transferring the minus is reproduced.

**Comment by uc-ai2** [comment]
Hello, @parrenin!
A fix for this issue will be included in the next release. Don't miss updates.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by parrenin** [comment]
Yes, it works.
Thank you for the fix!
