### ISSUE TITLE
Incorrect oval bullet which should be circular

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2209]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.3

### Expected Behavior

In the attached .docx document, there is a bullet list with circles.
The second circle actually should appear as a circle, like the other ones.

### Actual Behavior

The second bullet is oval.

### Reproduction Steps

Steps to reproduce:
- Open the attached .docx file in OO
- Open it in Word
- Compare the bullets
- 
[bug-OO-bullet.docx](https://github.com/ONLYOFFICE/DocumentServer/files/11223736/bug-OO-bullet.docx)

**Comment by maruacat** [comment]
Hello, @parrenin!
I can confirm - this is bug, issue 62160 in our private issue tracker.
Thank you for report.

**Comment by HectorB-2020** [comment]
@parrenin, please take a look at other issues related to the bullet lists.

- https://github.com/ONLYOFFICE/DesktopEditors/issues/317
- https://github.com/ONLYOFFICE/DesktopEditors/issues/469
- https://github.com/ONLYOFFICE/DesktopEditors/issues/501
- https://github.com/ONLYOFFICE/DesktopEditors/issues/546
- https://github.com/ONLYOFFICE/DesktopEditors/issues/1095
- https://github.com/ONLYOFFICE/DocumentServer/issues/1127
- https://github.com/ONLYOFFICE/DesktopEditors/issues/1131

**Comment by parrenin** [comment]
I think this bug is fixed in 7.4.0.

**Comment by maruacat** [comment]
Hello, @parrenin 
The issue has indeed been fixed and is not reproducible in version 7.4.0 for Linux systems, but it still exists on macOS. Therefore, we will continue to work on fixing the issue for macOS and will keep this issue open for now.
Thanks for your feedback and have a nice day!
