### ISSUE TITLE
Spreadsheet editor conditional formatting, fill series breaks the range

### ISSUE THREAD

**Issue by sunhunter777** [ONLYOFFICE/DocumentServer#2716]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.2.2.56

### Expected Behavior

In the table, one of the columns has a conditional formatting rule configured. The rule is configured
![Screenshot_1](https://github.com/ONLYOFFICE/DocumentServer/assets/168278527/532e1298-07e5-4ddc-91a2-533be1eb650d)
for the entire column or one range, it makes no difference. Some of the cells already have data (formula) and I want to use "Fill" to fill the formula in new rows.
![Screenshot_2](https://github.com/ONLYOFFICE/DocumentServer/assets/168278527/0d7c848c-bcfd-4b59-8ffb-e32190ac878a)
 I select the cell above, move the cursor to the lower right corner of the selected cell, and drag the cursor down. I'm expecting the formula to be copied into new cells with the cell references changed, then conditional formatting applied to the formula results

### Actual Behavior

The formula is copied perfectly, but the range specified in the conditional formatting rule is split into several parts (separated by a semicolon, the range before the "fill", each "filled" cell separately, the range after the "fill")
![Screenshot_3](https://github.com/ONLYOFFICE/DocumentServer/assets/168278527/ce9d5b98-c9ee-43b2-a101-32e67e20c38b)
![Screenshot_4](https://github.com/ONLYOFFICE/DocumentServer/assets/168278527/8807d0f3-ec56-4526-9fa7-cce2b01c4c3c)

### Reproduction Steps

1. Set conditional formatting for column range
2. Fill any data
3. Use fill series to fill other cells
4. Check range in conditional formatting

### Additional information

This bug does not look very serious, however, when actively working in a table with deleting and adding rows, the range of conditional formatting reaches some limit and the document does not open, the document loads endlessly

**Comment by VladimirProkofiev52** [comment]
Hello!
@sunhunter777 I observed that you're utilizing an older version of the editor, version 7.2.2. Is the problem still present in the latest version, 8.0.1? 
Regrettably, I couldn't replicate the issue you're experiencing. 
Would you mind attaching the file where the problem occurs, please?

**Comment by sunhunter777** [comment]
I apologize for the long response, I was updating onlyoffice. Below is a gif with a reproduction of the error, also attached is a file where the problem appears
![Onlyoffice](https://github.com/ONLYOFFICE/DocumentServer/assets/168278527/8adb2241-0132-4101-9177-e785428dcf56)

[Example.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/15385359/Example.xlsx)

**Comment by VladimirProkofiev52** [comment]
I can confirm - this is bug, issue #68907.
Thanks for your report!

**Comment by VladimirProkofiev52** [comment]
Hello!
@sunhunter777 I'm happy to inform you that your issue has been fixed! The changes will be available in the next major release of our editor.

**Comment by Rita-Bubnova** [comment]
DocumentServer v9.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by hubergitgif** [comment]
This issue still exists. When adding a new row between 2 rows, the conditional formatting rules go weird.
This happens not with Excel or any other one. Only Onlyoffice. You said it was fixed, do we need to change a setting or something to make the fix work?
