### ISSUE TITLE
nodehun dependency of spellchecker fails to build with nodejs 10

### ISSUE THREAD

**Issue by onny** [ONLYOFFICE/DocumentServer#304]
**Do you want to request a *feature* or report a *bug*?** 
bug

**What is the current behavior?**
DocumentServer fails to build. It stops with an error when trying to build nodehun nodejs dependency for the spellchecker.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This error occours only when nodejs 10 or higher is installed and used. So to reproduce it, just run: npm install nodehun (or install custom nodehun from the onlyoffice github repo)

**What is the expected behavior?**
nodehun compilation should pass also with nodejs 10 or higher.

**Did this work in previous versions of DocumentServer?**
I dont think so

**DocumentServer version:**
5.1.3

**Operating System:**
ArchLinux x64

**Logs:**
Here are the relevant logs from make:
```
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::createNewNodehunFinish(uv_work_t*, int)â€™:
../src/post0.12.0/nodehun.cpp:92:38: error: no matching function for call to â€˜v8::Function::NewInstance(int, v8::Handle<v8::Value>*)â€™
   argv[1] = cons->NewInstance(1, &ext);
```
and this is the complete log:
```

> nodehun@2.0.11 install /home/onny/node_modules/nodehun
> node-gyp rebuild

make: Entering directory '/home/onny/node_modules/nodehun/build'
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/affentry.o
In file included from ../src/hunspell/src/hunspell/affentry.cxx:9:
../src/hunspell/src/hunspell/affentry.hxx:30:105: warning: converting to non-pointer type â€˜short unsigned intâ€™ from NULL [-Wconversion-null]
   struct hentry *      check_twosfx(const char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                                                         ^~~~
../src/hunspell/src/hunspell/affentry.hxx:93:114: warning: converting to non-pointer type â€˜short unsigned intâ€™ from NULL [-Wconversion-null]
   struct hentry *   check_twosfx(const char * word, int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                                                                  ^~~~
../src/hunspell/src/hunspell/affentry.cxx: In member function â€˜int PfxEntry::test_condition(const char*)â€™:
../src/hunspell/src/hunspell/affentry.cxx:113:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
          case '.': if (!pos) { // dots are not metacharacters in groups: [.]
                    ^~
../src/hunspell/src/hunspell/affentry.cxx:120:5: note: here
     default: {
     ^~~~~~~
../src/hunspell/src/hunspell/affentry.cxx: In member function â€˜int SfxEntry::test_condition(const char*, const char*)â€™:
../src/hunspell/src/hunspell/affentry.cxx:501:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
         case '.': if (!pos) { // dots are not metacharacters in groups: [.]
                   ^~
../src/hunspell/src/hunspell/affentry.cxx:516:5: note: here
     default: {
     ^~~~~~~
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/affixmgr.o
In file included from ../src/hunspell/src/hunspell/affixmgr.cxx:13:
../src/hunspell/src/hunspell/affentry.hxx:30:105: warning: converting to non-pointer type â€˜short unsigned intâ€™ from NULL [-Wconversion-null]
   struct hentry *      check_twosfx(const char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                                                         ^~~~
../src/hunspell/src/hunspell/affentry.hxx:93:114: warning: converting to non-pointer type â€˜short unsigned intâ€™ from NULL [-Wconversion-null]
   struct hentry *   check_twosfx(const char * word, int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                                                                  ^~~~
../src/hunspell/src/hunspell/affixmgr.cxx: In member function â€˜int AffixMgr::parse_convtable(char*, IStrMgr*, RepList**, const char*)â€™:
../src/hunspell/src/hunspell/affixmgr.cxx:3671:58: warning: argument to â€˜sizeofâ€™ in â€˜int strncmp(const char*, const char*, size_t)â€™ call is the same expression as the second source; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]
                              if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                                          ^~~~~~~~~~~~~~~
../src/hunspell/src/hunspell/affixmgr.cxx: In member function â€˜int AffixMgr::encodeit(affentry&, char*)â€™:
../src/hunspell/src/hunspell/affixmgr.cxx:1092:12: warning: â€˜char* strncpy(char*, const char*, size_t)â€™ specified bound 20 equals destination size [-Wstringop-truncation]
     strncpy(entry.c.conds, cs, MAXCONDLEN);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/csutil.o
../src/hunspell/src/hunspell/csutil.cxx: In function â€˜void strlinecat(char*, const char*)â€™:
../src/hunspell/src/hunspell/csutil.cxx:411:24: warning: â€˜char* strncpy(char*, const char*, size_t)â€™ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
                 strncpy(dest, s, len);
                 ~~~~~~~^~~~~~~~~~~~~~
../src/hunspell/src/hunspell/csutil.cxx:407:21: note: length computed here
     int len = strlen(s);
               ~~~~~~^~~
../src/hunspell/src/hunspell/csutil.cxx: In function â€˜char* mystrrep(char*, const char*, const char*)â€™:
../src/hunspell/src/hunspell/csutil.cxx:567:16: warning: â€˜char* strncpy(char*, const char*, size_t)â€™ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
         strncpy(pos, rep, replen);
         ~~~~~~~^~~~~~~~~~~~~~~~~~
../src/hunspell/src/hunspell/csutil.cxx:552:26: note: length computed here
       int replen = strlen(rep);
                    ~~~~~~^~~~~
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/dictmgr.o
../src/hunspell/src/hunspell/dictmgr.cxx: In member function â€˜int DictMgr::parse_file(const char*, const char*)â€™:
../src/hunspell/src/hunspell/dictmgr.cxx:102:37: warning: this statement may fall through [-Wimplicit-fallthrough=]
                        pdict->region=NULL;
                                     ^
../src/hunspell/src/hunspell/dictmgr.cxx:103:21: note: here
                     case 2: //deliberate fallthrough
                     ^~~~
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/filemgr.o
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/hashmgr.o
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/hunspell.o
../src/hunspell/src/hunspell/hunspell.cxx: In member function â€˜int Hunspell::spell(const char*, int*, char**)â€™:
../src/hunspell/src/hunspell/hunspell.cxx:378:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
             *info += SPELL_ORIGCAP;
../src/hunspell/src/hunspell/hunspell.cxx:379:6: note: here
      case NOCAP: {
      ^~~~
../src/hunspell/src/hunspell/hunspell.cxx:448:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             }
             ^
../src/hunspell/src/hunspell/hunspell.cxx:450:6: note: here
      case INITCAP: {
      ^~~~
../src/hunspell/src/hunspell/hunspell.cxx: In member function â€˜int Hunspell::suggest(char***, const char*)â€™:
../src/hunspell/src/hunspell/hunspell.cxx:750:30: warning: this statement may fall through [-Wimplicit-fallthrough=]
                     capwords = 1;
                     ~~~~~~~~~^~~
../src/hunspell/src/hunspell/hunspell.cxx:751:6: note: here
      case HUHCAP: {
      ^~~~
../src/hunspell/src/hunspell/hunspell.cxx:874:24: warning: this statement may fall through [-Wimplicit-fallthrough=]
               capwords = 1;
               ~~~~~~~~~^~~
../src/hunspell/src/hunspell/hunspell.cxx:875:11: note: here
           case HUHCAP: {
           ^~~~
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/hunzip.o
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/phonet.o
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/replist.o
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/strmgr.o
  CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/suggestmgr.o
../src/hunspell/src/hunspell/suggestmgr.cxx: In member function â€˜char* SuggestMgr::suggest_gen(char**, int, char*)â€™:
../src/hunspell/src/hunspell/suggestmgr.cxx:1723:12: warning: â€˜char* strncpy(char*, const char*, size_t)â€™ output truncated before terminating nul copying 3 bytes from a string of the same length [-Wstringop-truncation]
     strncpy(ds, MORPH_TERM_SFX, MORPH_TAG_LEN);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  AR(target) Release/obj.target/src/hunspell/hunspell.a
  COPY Release/hunspell.a
  CXX(target) Release/obj.target/nodehun/src/nodehun.o
../src/nodehun.cpp:5:2: warning: #warning "Nodehun is no longer being actively maintained. Please email nathanjsweet@gmail.com If you are interested in taking over the project." [-Wcpp]
 #warning "Nodehun is no longer being actively maintained. Please email nathanjsweet@gmail.com If you are interested in taking over the project."
  ^~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::createNewNodehunFinish(uv_work_t*, int)â€™:
../src/post0.12.0/nodehun.cpp:92:38: error: no matching function for call to â€˜v8::Function::NewInstance(int, v8::Handle<v8::Value>*)â€™
   argv[1] = cons->NewInstance(1, &ext);
                                      ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate: â€˜v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) constâ€™
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8.h:3848:44: note:   candidate expects 3 arguments, 2 provided
/home/onny/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate: â€˜v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) constâ€™
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8.h:3851:44: note:   candidate expects 1 argument, 2 provided
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::isCorrect(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:165:49: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       String::Utf8Value arg0(args[0]->ToString());
                                                 ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::isCorrectSync(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:186:49: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       String::Utf8Value arg0(args[0]->ToString());
                                                 ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::spellSuggest(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:245:49: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       String::Utf8Value arg0(args[0]->ToString());
                                                 ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::spellSuggestSync(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:266:47: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value arg0(args[0]->ToString());
                                               ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::spellSuggestions(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:301:49: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       String::Utf8Value arg0(args[0]->ToString());
                                                 ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::spellSuggestionsSync(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:322:47: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value arg0(args[0]->ToString());
                                               ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::addRemoveWordInit(const v8::FunctionCallbackInfo<v8::Value>&, bool)â€™:
../src/post0.12.0/nodehun.cpp:504:47: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value arg0(args[0]->ToString());
                                               ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::addRemoveWordInitSync(const v8::FunctionCallbackInfo<v8::Value>&, bool)â€™:
../src/post0.12.0/nodehun.cpp:545:47: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value arg0(args[0]->ToString());
                                               ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::stem(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:607:53: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       v8::String::Utf8Value arg0(args[0]->ToString());
                                                     ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::stemSync(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:626:51: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     v8::String::Utf8Value arg0(args[0]->ToString());
                                                   ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::generate(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:701:53: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       v8::String::Utf8Value arg0(args[0]->ToString());
                                                     ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:702:53: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       v8::String::Utf8Value arg1(args[1]->ToString());
                                                     ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::generateSync(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:722:51: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     v8::String::Utf8Value arg0(args[0]->ToString());
                                                   ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:723:51: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     v8::String::Utf8Value arg1(args[1]->ToString());
                                                   ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::analyze(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:790:53: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
       v8::String::Utf8Value arg0(args[0]->ToString());
                                                     ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: In static member function â€˜static void Nodehun::SpellDictionary::analyzeSync(const v8::FunctionCallbackInfo<v8::Value>&)â€™:
../src/post0.12.0/nodehun.cpp:809:51: warning: â€˜v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)â€™ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     v8::String::Utf8Value arg0(args[0]->ToString());
                                                   ^
In file included from /home/onny/.node-gyp/10.1.0/include/node/v8.h:26,
                 from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/onny/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro â€˜V8_DEPRECATEDâ€™
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp: At global scope:
/home/onny/.node-gyp/10.1.0/include/node/node.h:513:43: warning: cast between incompatible function types from â€˜void (*)(v8::Handle<v8::Object>, v8::Handle<v8::Object>)â€™ {aka â€˜void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>)â€™} to â€˜node::addon_register_funcâ€™ {aka â€˜void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)â€™} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/onny/.node-gyp/10.1.0/include/node/node.h:547:3: note: in expansion of macro â€˜NODE_MODULE_Xâ€™
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/post0.12.0/nodehun.cpp:860:1: note: in expansion of macro â€˜NODE_MODULEâ€™
 NODE_MODULE(nodehun, Nodehun::SpellDictionary::Init);
 ^~~~~~~~~~~
In file included from /home/onny/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../src/post0.12.0/nodehun.hpp:5,
                 from ../src/post0.12.0/nodehun.cpp:1,
                 from ../src/nodehun.cpp:12:
/home/onny/.node-gyp/10.1.0/include/node/v8.h: In instantiation of â€˜void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]â€™:
/home/onny/.node-gyp/10.1.0/include/node/node_object_wrap.h:85:78:   required from here
/home/onny/.node-gyp/10.1.0/include/node/v8.h:9227:16: warning: cast between incompatible function types from â€˜v8::WeakCallbackInfo<node::ObjectWrap>::Callbackâ€™ {aka â€˜void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)â€™} to â€˜Callbackâ€™ {aka â€˜void (*)(const v8::WeakCallbackInfo<void>&)â€™} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [nodehun.target.mk:102: Release/obj.target/nodehun/src/nodehun.o] Error 1
make: Leaving directory '/home/onny/node_modules/nodehun/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.14.0-gnu-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/onny/node_modules/nodehun
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/onny/package.json'
npm WARN onny No description
npm WARN onny No repository field.
npm WARN onny No README data
npm WARN onny No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodehun@2.0.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodehun@2.0.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/onny/.npm/_logs/2018-05-19T15_07_13_594Z-debug.log
```
**Workaround:**
Temporary workaround is downgrading to nodejs 9.X

**Comment by Wulf** [comment]
Related to [nodehun !63](https://github.com/Wulf/nodehun/issues/63).

**Comment by Wulf** [comment]
This should hopefully be resolved now!

**Comment by Ke1i** [comment]
I guess this is the reason the spellchecker doesn't work in the latest version of ONLYOFFICE-DocumentServer-5.1.4.
Here are some files from /var/log/onlyoffice/documentserver/spellchecker/
[err.log](https://github.com/ONLYOFFICE/DocumentServer/files/2041478/err.log)
[out.log](https://github.com/ONLYOFFICE/DocumentServer/files/2041479/out.log)
Running Onlyoffice-DocumentServer on Ubuntu Server 18.04 LTS, Nodejs v8.10.0

**Comment by chrispydizzle** [comment]
This still happens, at least, I ran into this weekend. The package.json for this module is pointing at the github repo for nodehun, which is either broken or out of date. When I change it to the current version that node is hosting (2.0.12) it works just fine.

**Comment by onny** [comment]
Bug still present in DocumentServer version 2.5.0

**Comment by onny** [comment]
Bug still present in DocumentServer version 5.2.3 since the nodehun module fork here https://github.com/ONLYOFFICE/nodehun wasn't yet updated to version 2.0.12

**Comment by ShockwaveNN** [comment]
@onny yeap, issue is still actual, since upgrading to latest nodehun is not an easy process for us, because we used fork of nodehun.

**Comment by ndlrx** [comment]
I still get the issue with my Ubuntu 18.04 and the DocumentServer 5.2.3.

I'm installed the DocumentServer with nodejs 8, then rebuilding the spellchecker and it's solved.

now I get an error about the converter, 'Download failed' when trying to edit the office file. When I check th log, it's about ssl handshake error. SO i just upgrade the nodejs to v10, and it's solved.

**Comment by ShockwaveNN** [comment]
I just checked - you can use nodejs 10 after reinstall of `node_modules` in DocumentServer 5.2.7 and seems everything works fine.
I'll close this issue, but feel free asking any question if any left

**Comment by jasle** [comment]
I just tried to build the forked nodehun and it seems to fail with the same error. The upstream nodehun build fine.
```
> nodehun@3.0.2 install
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@12.21.0 | linux | x64
gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/nodehun/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jasle/.cache/node-gyp/12.21.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/jasle/.cache/node-gyp/12.21.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/jasle/.cache/node-gyp/12.21.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/nodehun',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/tmp/nodehun/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/src/nothing.a
  COPY Release/nothing.a
make: *** No rule to make target 'Release/obj.target/hunspell/src/hunspell/src/hunspell/affentry.o', needed by 'Release/obj.target/src/hunspell.a'.  Stop.
make: Leaving directory '/tmp/nodehun/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.11.2-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/nodehun
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /tmp/nodehun
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
```

**Comment by ShockwaveNN** [comment]
@jasle Try same command with node js v10, since we do not support nodejs v12 currently (we're working on it)
Also please note there is [known issues](https://github.com/npm/cli/issues/2774) with npm v7, so also use npm v6

**Comment by jasle** [comment]
Thanks for the quick reply!
I have also tried running it with `node v10.24.0` and `npm 6.14.9`, but it still fails with the same error message. Building the upstream `nodehun` works, even with a recent node and npm version.

**Comment by ShockwaveNN** [comment]
@jasle could you try to build using [this Dockerfile](https://github.com/ONLYOFFICE/build_tools/blob/master/Dockerfile) and compare dependency version

**Comment by jasle** [comment]
@ShockwaveNN tried build server 6.1.1 using the Dockerfile tagged with v6.1.17 and got the same error message.

I am not really sure which tagged version of the Dockerfile should work with which version of the server, should this versions work together?

And thanks again for your awesome support!

**Comment by ShockwaveNN** [comment]
@jasle Try to build it from master, and I think it's better to create new issue in build_tools repo if build from master failing, since this issue is 3 years old and we're completely change our build process
