### ISSUE TITLE
AMQP cannot establish connection since upgrade to rabbitmq-server 4.1

### ISSUE THREAD

**Issue by WhoAmI0501** [ONLYOFFICE/DocumentServer#3204]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.3.2-19

### Expected Behavior

The AMQP component of Onlyoffice Documentserver should establish a connection to the rabbitmq-server 4.1 instance and the documentserver should work normally.

### Actual Behavior

Both, ds-converter.service and ds-docservice.service, returned the following log messages:

```
Apr 16 02:41:53 cloud sh[1035]: [2025-04-16T02:41:53.863] [ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: read ECONNRESET
Apr 16 02:41:53 cloud sh[1035]:     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

The Healthcheck Endpoint returned, that something is not okay with my Documentserver and editing documents in Nextcloud didn't worked anymore.

This worked before with rabbitmq-server 4.0 and also started to work again after an downgrade to rabbitmq-server 4.0.

The TCP socket was still reachable with 4.1 (tested it via nc -vz), which is the reason why i suspect, that there is maybe some incompatibility between the used AMQP client library and the new rabbitmq-server 4.1 version?

### Reproduction Steps

Debian 12 amd64 server
 
1. Install rabbitmq-server 4.1
2. Install OnlyOffice Documentserver 8.3.2-19
3. Try to use Documentserver / see its logs

**Comment by WhoAmI0501** [comment]
The changelog of rabbitmq-server states the following breaking change with 4.1:

> Initial AMQP 0-9-1 Maximum Frame Size
>
> Before a client connection can negotiate a maximum frame size (frame_max), it must authenticate
> successfully. Before the authenticated phase, a special lower frame_max value
> is used.
>
> With this release, the value was increased from the original 4096 bytes to 8192
> to accommodate larger [JWT tokens](https://www.rabbitmq.com/docs/oauth2).
>
> Clients that do override frame_max now must use values of 8192 bytes or greater.
> We recommend using the default server value of 131072: do not override the frame_max
> key in rabbitmq.conf and do not set it in the application code.
>
> [amqplib](https://github.com/amqp-node/amqplib/) is a popular client library that has been using
> a low frame_max default of 4096. Its users must [upgrade to a compatible version](https://github.com/amqp-node/amqplib/blob/main/CHANGELOG.md#v0107)
> (starting with 0.10.7) or explicitly use a higher frame_max.

**Comment by WhoAmI0501** [comment]
While digging a bit deeper, i found out, that OnlyOffice currently uses amqplib 0.8.0 ([package.json](https://github.com/ONLYOFFICE/server/blob/master/Common/package.json)).

**Comment by dani** [comment]
Waiting for a proper fixe, you can workarround this issue by adding this in your config
```json
  "rabbitmq": {
    "url": "amqp://localhost:5672?frameMax=0"
  }
```

**Comment by Inteum** [comment]
> adding this in your config
This did not solve the problem

**Comment by SeanChengN** [comment]
I use docker deployment and downgrade rabbitmq to 4.0 to use

**Comment by smallcms** [comment]
Have same issue, like @SeanChengN. Downgraded to rabbitmq:4.0 in docker-compose.override.yml
```
  onlyoffice-rabbitmq:
    image: rabbitmq:4.0
```

**Comment by Groggy** [comment]
> Waiting for a proper fixe, you can workarround this issue by adding this in your config
> ```json
>   "rabbitmq": {
>     "url": "amqp://localhost:5672?frameMax=0"
>   }
> ```

This fixed the issue for me.

If you're using docker, append `?frameMax=0` to the `AMQP_URI` environment variable.

**Comment by smallcms** [comment]
> If you're using docker, append `?frameMax=0` to the `AMQP_URI` environment variable.

Do you test it? netcat test fails to resolve hostname...

**Comment by wabadoo-wabadee** [comment]
I, too had the problem but was unable to find this issue for a long time so I want to add the log entries which I searched with:

`error: FORMATTER CRASH: {"closing AMQP connection ~tp (~ts):~nfailed to negotiate connection parameters: ~ts",[<0.771.0>,<<"172.18.0.3:33800 -> 172.18.0.2:5672">>,"3s","negotiated frame_max = 4096 is lower than the minimum allowed value (8192)"]}`

**Comment by leppa** [comment]
> I did not find a solution for using with the updated rabbitmq

@Lakhtion, read @dani's and my comments above. The workaround works for me with `4.1.0` without any issues.

**Comment by zpfhyj** [comment]
I have same problem when I installed onlyoffice to k8s cluster useing helm.  Finally I used rabbitmq 4.0.9 version to solve this problem.

**Comment by igwyd** [comment]
It's fixed at:https://github.com/ONLYOFFICE/server/commit/f2f0e05af9392bfa26d3e2039b708c8b4d78eecd and will be released in the next major release.

**Comment by Mywk** [comment]
For those using Docker Compose, my workaround is to just add this to the service definition:
```
entrypoint:
  - /bin/sh
  - -c
  - >
    echo '{"rabbitmq": {"url": "amqp://onlyoffice-rabbitmq:5672?frameMax=0"}}' > /etc/onlyoffice/documentserver/default.json &&
    /app/ds/run-document-server.sh

```

**Comment by Buuuntyyy** [comment]
> > Waiting for a proper fixe, you can workarround this issue by adding this in your config
> >   "rabbitmq": {
> >     "url": "amqp://localhost:5672?frameMax=0"
> >   }
> 
> This fixed the issue for me.
> 
> If you're using docker, append `?frameMax=0` to the `AMQP_URI` environment variable.

Where did you paste it ? How did you do ?
I'm running it in in the Kube architecture, but after many hours, it still doesn't work.

Thanks !

**Comment by igwyd** [comment]
Hello @Buuuntyyy, you can use rabbitmq 4.0.9 before our release with fix. You can get it from the bitnami chart version 15.5.3 for example: 
```
helm install rabbitmq bitnami/rabbitmq \
  --version 15.5.3 \
  --set persistence.storageClass=<your_storage_class>
```

**Comment by WhoAmI0501** [comment]
I just want to confirm, that the new v9 Release is fixing the problematic behavior on all of my servers. OnlyOffice v9 seems to be running flawless with RabbitMQ 4.1.

Thanks to all maintainers for fixing it! :)
(cc @igwyd)

**Comment by Menghini** [comment]
Updating to 9.0.0 worked for me without any issues.
