### ISSUE TITLE
Embedded Viewer is rendering Links not in place

### ISSUE THREAD

**Issue by jfschubert** [ONLYOFFICE/DocumentServer#3340]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

9.0.3

### Expected Behavior

The Link is clickable in the selected location

### Actual Behavior

The Link is rendered above the actual position an is not clickable

https://github.com/user-attachments/assets/00baab57-6695-4ba3-a05f-99265c497679

however:

https://github.com/user-attachments/assets/29939918-9214-43e8-b527-178f08dece08

 Readjusting zoomlevel fixes the positioning but still not clickable

### Reproduction Steps

Open PDF with links in the embedded viewer. Links should not be clickable
Also this happens with .docx documents too but there the reproduction is not guarantied.

### Additional information

If needed we can deliver the .pdf files that have the issue.

**Comment by TatianaKirillova** [comment]
Hello, @jfschubert 
Thanks for your request!
 I can confirm that the problem exists, issue 76182 for your problem.

**Comment by TatianaKirillova** [comment]
Hello @jfschubert I'm happy to report that the issue is fixed with [this commit](https://github.com/ONLYOFFICE/web-apps/commit/066baaeee7a83c56caf4542f08a8c9a144101318) and will be included in the next release. Don't miss updates. Have a nice day!

**Comment by Rita-Bubnova** [comment]
DocumentServer v9.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by jfschubert** [comment]
Still persists on Version 9.1 and Verion 9.2. in the Embedded Viewer.

**Comment by ElenaMaaya** [comment]
> Still persists on Version 9.1 and Verion 9.2. in the Embedded Viewer.

Hello @jfschubert !
Could you please check the issue on version 9.2.1? We were unable to reproduce the problem on Windows 11 Pro using version  9.2.1.
If the issue still occurs for you, please create a separate issue ticket. 
Make sure to include the following:
exact details of your system configuration;
a video demonstrating the problem;
any test file needed to reproduce the issue.

Thank you in advance for your cooperation!
