### ISSUE TITLE
Problems to print document in Firefox

### ISSUE THREAD

**Issue by frankschmid** [ONLYOFFICE/DocumentServer#384]
In Firefox browser the print-button opens the "save-as-window" instead of the "print-window".  Same happens when pressing "strg + p". (Firefox-Version: 62.0 )

**Comment by ShockwaveNN** [comment]
@frankschmid we do not sure, cause pressing ctrl+p in Chrome on any page cause opening Chrome Print Preview window, but pressing ctrl+p on any page in Firefox cause opening Print Setting from OS.
We need to discuss with a team this question.

**Comment by ShockwaveNN** [comment]
Probably related to bug 16000 in our private bug tracker

**Comment by ShockwaveNN** [comment]
Also 34613
Currently there is no known way to show print window in Firefox like in Chrome by pressing ctrl+p

**Comment by ShockwaveNN** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=911444

**Comment by huisnotacouncillor** [comment]
@ShockwaveNN Hi，has this problem been solved?

**Comment by ShockwaveNN** [comment]
@huisnotacouncillor Sorry, no news

**Comment by huisnotacouncillor** [comment]
@ShockwaveNN What about print generated PDF documents?

**Comment by ShockwaveNN** [comment]
@huisnotacouncillor both problem mentioned in this issue currently has no changes

**Comment by ShockwaveNN** [comment]
DocumentServer v6.3.0 is released. This problem should be fixed

**Comment by oszymanski** [comment]
The problem seems to still persist in Firefox. I've tested that on the latest image of Developer Edition (6.4) and the latest Mozilla Firefox (78.15.0esr). Clicking the print button and using the key shortcut still causes to open save-as-window instead of print-window.

**Comment by oszymanski** [comment]
Ok, on the latest stable Firefox it actually works fine. Why is Mozilla making esr version a default download from the site is beyond my understanding though. Thanks for the answer and sorry for taking your time.
