### ISSUE TITLE
Displacement distance between mouse cursor and cell cursor.

### ISSUE THREAD

**Issue by amokmen** [ONLYOFFICE/DocumentServer#500]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Could not choose cell under cursor. Instead is choosing another cell, in some distance (upper left from current cursor position). Scaling in browser did not help.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Take monitor 2560x1440 px (I have 2 monitors, second is FullHD - there are all right).
2) Windows 10 with scale 150%.
3) Open any version OO (CE or cloud) in Opera (scale 100%) and open spreadsheet.
4) Click on any cell under cursor --> cell **in some distance** would be chosen instead.
5) If you would scale Opera (in menu) and scale in Spreadsheet Editor (by Ctrl+"+/-") --> you could get different displacement distance - from upper left to lower right.

**What is the expected behavior?**
I move cursor to needed cell and choose it.

**Did this work in previous versions of DocumentServer?**
Probably I met this bug before, on FullHD monitor...

**DocumentServer version:**
Spreadsheet Editor 5.2.4 CE
&
Spreadsheet Editor 5.2.7

**Operating System:**
Windows 10 x64

**Browser version:**
Opera 57.0.3098.116

**Comment by Rita-Bubnova** [comment]
Hello, @amokmen.
Thank you. I can confirm - this is a bug, issue 40527 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This problem is fixed in  https://github.com/ONLYOFFICE/sdkjs/commit/4db81216d64914cba0f0b2329eadab0869cb85d1
We release this fix in version 5.3.

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.

**Comment by ksceniev** [comment]
This issue persists in DocumentServer 8.1.1 when using Chrome web browser.

**Comment by Rita-Bubnova** [comment]
> This issue persists in DocumentServer 8.1.1 when using Chrome web browser.

This is another https://github.com/ONLYOFFICE/DocumentServer/issues/2859.
