### ISSUE TITLE
Horizontal scroll not working properly

### ISSUE THREAD

**Issue by markovic-nikola** [ONLYOFFICE/DocumentServer#536]
**Do you want to request a *feature* or report a *bug*?**
I want to report a small bug when using a spreadsheet.

**What is the current behavior?**
I have 2 scroll wheels on my mouse, when using horizontal wheel it causes spreadsheet to scroll both vertically and horizontally at the same time which is not a correct behavior.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When using horizontal wheel only:
![Peek 2019-04-03 15-00](https://user-images.githubusercontent.com/16388545/55480805-587ce380-5621-11e9-8227-9ec4877acf80.gif)

**What is the expected behavior?**
Spreadsheet should scroll only horizontally.

**DocumentServer version:**
ONLYOFFICE Desktop Editors version 5.2.83.480

**Operating System:**
Manjaro Linux 18.0.4 (Codename: Illyria)
KDE version: plasmashell 5.15.3

**Comment by Rita-Bubnova** [comment]
Hello, @markovic-nikola.
Thank you. I can confirm - this is a bug, issue 41073 in our internal issue tracker.

**Comment by FabienSailliet** [comment]
Hi, is there any update on this ? I have the same bug on Kubuntu 20.04 with ONLYOFFICE 6.3.1.56, with both the mouse horizontal wheel and the touch pad.

**Comment by Rita-Bubnova** [comment]
@FabienSailliet, sorry, currently there is no news.

**Comment by Davincible** [comment]
Since we're another year ahead, any chance of this getting fixed? :D Would be really nice

**Comment by ShockwaveNN** [comment]
@Davincible sorry, no news but I raised this question to developers once again

**Comment by crlorentzen** [comment]
👍 
Seen on:
ONLYOFFICE Desktop Editors version 7.0.1.37
Windows 10 (21H2)

**Comment by swssl** [comment]
Also occurs in ONLYOFFICE Desktop Editors Version 7.1.1.57 on Kubuntu 22.04 LTS
(KDE Plasma Version: 5.24.4; KDE Frameworks Version: 5.92.0; Qt Version: 5.15.3)

**Comment by Vegardbeider** [comment]
Same problem for me. Onlyoffice version 7.1.1.57. Using Fedora 36 with i3wm. 
Both with laptop-trackpad and logitech MX master 3s

**Comment by S-trace** [comment]
I'm affected too. Manjaro, OnlyOffice v7.2.1.36, MX Master 3.

Is it OK to keep a simple but annoying UI bug affecting basics of UX for 3+ years?

**Comment by TendiF** [comment]
Also happen to me 

OS Name	Microsoft Windows 10 Home Single Language
Version	10.0.19044 Build 19044

ONLYOFFICE Desktop Editors version 7.2.1.36 (x64 exe package)

**Comment by cameronluke** [comment]
Same issue still exists. This issue majorly effects productivity when trying to scroll large datasets/tables.

Windows 10 Pro
Version 21H2 Build 19044.2251

ONLYOFFICE Desktop Editors version 7.2.1.36 (x64 exe package)

**Comment by andreig-kozminski** [comment]
Same Issue in last version avaible, I'm running it in docker on my VPS.... (online editor)

Docker: onlyoffice/documentserver:latest 
Build 7.2.1.34

**Comment by Mezgrman** [comment]
I'm affected as well!

**Comment by riblee** [comment]
I'm also affected on Manjaro ONLYOFFICE v7.4.1.36.
I'm using an MX Master 3.

**Comment by jmaximusix** [comment]
Still an issue, pls fix!

**Comment by mathpce** [comment]
I'm also affected when using two-fingers horizontal scroll on my Pop!_OS 22.04 LTS.
Using Shift+vertical scroll has a normal behaviour.

**Comment by barnabywalters** [comment]
Still an issue for me on kubuntu with version 7.5.1.23 (flatpak), when scrolling horizontally with the trackpad. It makes Onlyoffice near-unusable for any spreadsheet work, which almost always requires horizontal scrolling. I’m astonished this bug has been open for four years!

**Comment by vjuge** [comment]
I've the same issue here, using:

* mouse Logitech mx master 3
* having logiops software installed (but config not altering horizontal mouse wheel) : https://github.com/PixlOne/logiops
* only office 7.5.1.23
* fedora 38

I've managed to find a workaround: holding the shift key while scrolling makes the wheel working as expected

**Comment by atrushing** [comment]
I came here with the same concern but found that, for some users, this could be seen as a feature or intended behavior. 

While holding [Shift], both the scroll wheel and the side scroll wheel provide the desired behavior. When navigating very large sheets it can be useful to have a direct method to navigate diagonally through the page.

**Comment by Mezgrman** [comment]
> While holding [Shift], both the scroll wheel and the side scroll wheel provide the desired behavior. When navigating very large sheets it can be useful to have a direct method to navigate diagonally through the page.

Yes, but not as the default. Maybe scroll diagonally while holding Shift, but not the way it is right now.

**Comment by atrushing** [comment]
> Maybe scroll diagonally while holding Shift

That would create inconsistent logic and would be harder for training muscle memory. 

`IF: Shift + scroll - Then: scroll sideways`
`IF: Shift + Side Scroll - Then: scroll diagonally`

I don't think there is a perfect solution but, to me, the current implementation is the lesser of evils.

**Comment by Raphael124** [comment]
> I came here with the same concern but found that, for some users, this could be seen as a feature or intended behavior.
The problem to me is that the direct competition has one-to-one gestures for spreadsheets (i.e. if you scroll really horizontally, it goes horizontal, but if you scroll with a 20-degree angle it goes mostly horizontal but a bit vertical too)

**Comment by T3rminat0r** [comment]
Came here, wanting to report the same issue in the somewhat related cryptpad sheets (which use the same code, I believe...) Horizontal wheel should definitly scroll ONLY horizontally, unless there's use of any modifier keys...

**Comment by speeder658** [comment]
I've fixed mine with an autohoetkey script - if you don't have autohotkey installed, get it for free (v2) and then paste that into a script and run it :
`#HotIf WinActive("ahk_exe editors.exe")
A_HotkeyInterval := 1000  ; This is the default value (milliseconds).
A_MaxHotkeysPerInterval := 2000
WheelRight::+WheelRight
WheelLeft::+WheelLeft
return`

this will hold shift when you scroll sideways bringing back the original behaviour, If you want to have diagonal scrolling working when the shift key is pressed, add this
`+WheelRight::WheelRight
+WheelLeft::WheelLeft`

**Comment by bastiendmt** [comment]
Hi I'm facing the same issue. 
It works fine on firefox but not chrome. Doesn't even scroll on safari.

Would be nice to fix this ongoing 5 year bug

**Comment by jetrodn** [comment]
Still reproducing. 

Manjaro, OnlyOffice version 8.1.1.27 (deb), MX Master 3.

**Comment by markmb88** [comment]
Still an issue in Q4 2024.

Arch Linux, OnlyOffice version 8.1.1.27 (flatpak)

MX Master 3

**Comment by sgabenov** [comment]
Same issue with MacOS

**Comment by FlawlessCasual17** [comment]
Still an issue, I literally can't even scroll horizontally on an MS spreadsheet. The function is just gone.

**Comment by sgabenov** [comment]
Today i have opened an updated vesion and it works correctly with horizontal scrolling on Logi MX 3 mouse. OnlyOffice 8.2.2

**Comment by LuckySpecialist** [comment]
The problem has been fixed by https://github.com/ONLYOFFICE/sdkjs/commit/9709e95d4cee1bd560d421fc10b3afd4033c0c4b commit and is included in release 8.3.0.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.3.3 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
