### ISSUE TITLE
Spreadsheet editor: Filter - incorrect treatment of hidden rows

### ISSUE THREAD

**Issue by denisnone** [ONLYOFFICE/DocumentServer#74]
A bug

When you use filter and hide some rows, these hidden rows get affected by paste or autofill. 

To reproduce create a table with four rows, autoincrement the first column with: "1,2,3,4".
Fill some arbitrary data in the second column.
Enable filter for these 4 rows and 2 columns.
In first column's filter deselect values 2 and 3 to hide two rows in the middle.
Select two visible cells with data in the second column.
Paste something in these two selected cell. 
This pasted data gets pasted not only in visible cells, but also in hidden cells between two visible (with 2 and 3).

The expected behavior is that invisible cells don't get corrupted.

This bug affects all OSes, all browsers and belongs to internal document server logic.
Document server version: all, including 4.2.

**Comment by JohnPerkin** [comment]
Hello!
We have examined the issue. This is a bug that will be fixed in future versions of our product.
Thank you for the attention to ONLYOFFICE.

**Comment by denisnone** [comment]
Hello!

Do you have any information on when could it be fixed? 
It's strange that no one ever noticed this filter behavior before. 
No one uses filters? 

Best regards, Denis

**Comment by JohnPerkin** [comment]
Hello!
Unfortunately we can not specify the exaсt date of fix but we can say that the issue will be improved in nearest releases. You can keep up bug fixes in our [changelog](https://github.com/ONLYOFFICE/DocumentServer/releases).
Thank you for the interest in our product.

**Comment by trofim24** [comment]
In version [ONLYOFFICE-DocumentServer-4.4.1](https://github.com/ONLYOFFICE/DocumentServer/releases/tag/ONLYOFFICE-DocumentServer-4.4.1) we added ignoring of the lines hidden by the filter when copying data, autofill and other operations.
But we did not touch the Paste yet.

**Comment by denisnone** [comment]
Great news! 
Hope the Paste comes soon after that.

**Comment by denisnone** [comment]
Hello,
Any updates on Paste in filtered data?

**Comment by denisnone** [comment]
Hello,
How about Paste in filtered data? Any progress on that?

**Comment by denisnone** [comment]
Hi guys!

I suppose this will never be resolved? 
It's been a year and a half since this bug was raised.

**Comment by denisnone** [comment]
Hello, Rita!

Thanks for your reply!

To reproduce please try this:
1-3 Steps from your procedure
4. Fill A10 - "5"
5. Select A10 and CTRL-C
6. Select A2-A5. (Here you will eventually select only A2 and A5 because A3 and A4 are hidden)
7. Paste with CTRL-V
8. Turn off the filtration
9. BUG. You will see that you've pasted not only to A2 and A5, but also A3 and A4 were overwritten with "5". But they were hidden. 

You say that you've copied the MS Excel behavior, but this is not true! MS Excel never corrupts hidden lines. But in Onlyoffice we've corrupted the data in A3 and A4. 

Whatever you do in MS Excel, hidden data stay always intact. This is an axiom.
Onlyoffice:
![image](https://user-images.githubusercontent.com/22541657/46751147-5f561980-ccc2-11e8-98f7-ee9b1174e0bb.png)
MS Excel:
![image](https://user-images.githubusercontent.com/22541657/46751197-78f76100-ccc2-11e8-8788-8a019bd0fd7f.png)

**Comment by Rita-Bubnova** [comment]
In latest case you're decsribed - we really override filter data and we will fix it in future (but have no ETA)
But if we return to your firts problem (or steps 4-5 from your latest case fill A10:A13 and copy) - MS Excel override filtered data as well.

**Comment by denisnone** [comment]
Ok, thank you for your explanation.

The only thing I do not agree with is that you treat it as a low priority bug. 
The bug corrupts data and employers don't notice that while editing files. So the consequences of such a bug can be discovered months after the editing, sometimes when there is no simple way to recover from it.

So basically I should notify every single user of Onlyoffice, that there is a bug and he must never use multi paste with the filter active. And remind them every month so that they don't forget? 

No, this is ridiculous. In that case it's more simple and robust to use MS Excel without any collaboration at all, like in old days. 

Best regards, Denis.

**Comment by Rita-Bubnova** [comment]
We do not treat it as a low priority bug. Unfortunately, we do not have much  resources to fix it quicker because it's a part of another big task - multi-select which is scheduled for the next year. 
Apologies if this delay affects your productivity. We would appreciate your patience.

**Comment by Stanyer** [comment]
this is really a important bug.
It should add a special paste fuction that 'Paste only  in visible cells'

**Comment by denisnone** [comment]
> This issue fixed in а future major release.
> We've made a lot of fixes for this, so I can't give a commit.

Great news! Thanks.
Could you write a comment here when it's delivered to docker please?

**Comment by ShockwaveNN** [comment]
> Could you write a comment here when it's delivered to docker please

I'll close this issue as soon as it released

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles

**Comment by Stanyer** [comment]
This issue still exists in the Destop version, I really hope it get fixed.

**Comment by ShockwaveNN** [comment]
@Stanyer This issue is more than 5 years old, I think it's better to create a new issue for your problem

**Comment by Stanyer** [comment]
@ShockwaveNN okay
