### ISSUE TITLE
Copy and paste problem

### ISSUE THREAD

**Issue by fangjialong2019** [ONLYOFFICE/DocumentServer#750]
When one line of data is copied from Microsoft Excel to OnlyOffice, and the data in one cell is multiple lines of text, it will be split into multiple lines to OnlyOffice after pasting.

Modify SDKJS/cell/model/clipboard. Js file, optimize the parsing rules, can solve the problem, but I'm not sure it is correct.

Hope the official can provide the standard version of the solution

**Comment by fangjialong2019** [comment]
![image](https://user-images.githubusercontent.com/56392864/72530255-f0df0e80-38a9-11ea-9801-f6c989940e1a.png)

**Comment by fangjialong2019** [comment]
![image](https://user-images.githubusercontent.com/56392864/72530299-0c4a1980-38aa-11ea-99ce-c1393373f15f.png)

**Comment by fangjialong2019** [comment]
![image](https://user-images.githubusercontent.com/56392864/72530323-15d38180-38aa-11ea-9628-c267517cbfa6.png)

**Comment by fangjialong2019** [comment]
![image](https://user-images.githubusercontent.com/56392864/72530371-34397d00-38aa-11ea-8b5c-b4b9a781c516.png)

**Comment by fangjialong2019** [comment]
The above is my modification, thank you

**Comment by fangjialong2019** [comment]
[sdkjs.cell.model.clipboard.txt](https://github.com/ONLYOFFICE/DocumentServer/files/4071677/sdkjs.cell.model.clipboard.txt)

source code file

**Comment by Rita-Bubnova** [comment]
Hello, @fangjialong2019.
Thank you so much for your work, we really appreciate it, but at the moment our developers are working on their own solution of this problem.

**Comment by widechina** [comment]
@Rita-Bubnova.
This is an extremely good news ! Thanks a lot. Do you have an estimated date ?

**Comment by Rita-Bubnova** [comment]
In next major release possible.
This bug fixed https://github.com/ONLYOFFICE/sdkjs/commit/e12dbba9558bae5acde5a4cce98ef216a7bf8726 and https://github.com/ONLYOFFICE/sdkjs/commit/78281da4fbd159a4884795dda2b3eb6ffb62d48f.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.

**Comment by ThanhLNP** [comment]
Hi, I got the same error when copying from google sheet, could you please fix it

**Comment by ShockwaveNN** [comment]
@ThanhLNP This problem should be fixed, I think it's better to create a new issue, since OP message was from 2 year ago

**Comment by emanueol** [comment]
Seems this still not fixed as July 2025, just tried copy/paste 1 cell with multiple lines wrapped in doublequotes, and via Get data > load csv, and single multiline cell lines get loaded into multiple rows in onlyoffice.

Any suggestion ? This is critical for us.

<img width="2522" height="1309" alt="Image" src="https://github.com/user-attachments/assets/025e7d1e-0ee6-4829-bd17-08fefe74b3d5" />

**Comment by Dmitry-Kov** [comment]
Hi @emanueol,

Thanks for the clear example.

We reproduced the import and confirmed that multiline fields in a CSV are parsed into separate rows. This is standard for CSV parsing and gives the same result in Microsoft Excel, so ONLYOFFICE behaves identically for compatibility.

If you need to keep multiple lines in one cell, consider using XLSX or preprocessing the file before import.

**Comment by emanueol** [comment]
> This is standard for CSV parsing and gives the same result in Microsoft Excel, so ONLYOFFICE behaves identically for compatibility.

Sorry, but sadly, you are not correct in your assessment.
Here's proof that Excel can directly copy/paste or load a correct multi-line cell (and FYI: it also works in Google Sheets). 

So OPENOFFICE has a problem, that's why I kindly reported this issue, wondering when we could see the fix to this:

![Image](https://github.com/user-attachments/assets/daef103c-60ec-4864-949f-7938c894c1bc)

**Comment by Dmitry-Kov** [comment]
@emanueol,

Thanks for the clarification and the provided example.
Could you please create a separate issue specifically for this problem? This one has already been closed, and having a new issue will help us track it properly.

Thanks!

**Comment by emanueol** [comment]
> [@emanueol](https://github.com/emanueol),
> 
> Thanks for the clarification and the provided example. Could you please create a separate issue specifically for this problem? This one has already been closed, and having a new issue will help us track it properly.
> 
> Thanks!

What is the correct repo ? Theres 254
If the correct is DOCUMENT SERVER, then I don't know what to put on ISSUE Document Server O.S. since the issue is with the Windows **client** (not server), please advise the correct issue basics so I can smoothly open a ticket.

Thanks in advance ~

**Comment by Dmitry-Kov** [comment]
@emanueol, 

You can create the issue under Desktop and specify “OS: Windows.” We can easily move it to the appropriate repository later if needed.
